language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "nightly"
# command to install dependencies
install:
  - pip install -e .
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
